# Generated by Django 3.0.4 on 2020-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_company', '0003_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='strip_size',
            field=models.IntegerField(help_text="Strip's size"),
        ),
    ]
