# Generated by Django 3.0.4 on 2020-03-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline_company', '0005_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='airline_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline_company.AirlineCompany'),
        ),
    ]
