# Generated by Django 3.0.4 on 2020-03-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline_company', '0007_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airline_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline_company.AirlineCompany'),
        ),
        migrations.AddField(
            model_name='airport',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline_company.Captain'),
        ),
        migrations.AddField(
            model_name='employee',
            name='airline_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline_company.AirlineCompany'),
        ),
    ]
